### PR TITLE
Project restructure + BenchmarkDotNet migration

### PR DESCRIPTION
**Pull request by Aaronontheweb**
Restructured the project and junked the old build-system in favor of the standardized one we use in [Petabridge's projects](https://github.com/petabridge/petabridge-dotnet-new), which operates based on an extensible set of conventions we've already been using for years in Akka.NET.

Using this to put an end to the build server issues with all of the .NET versions et al. Going to bump all test projects to .NET Core 2.0 if this still has trouble.

### CODE REVIEW

**Comment by Horusiath** [comment]
> System.InvalidCastException : [A]System.Collections.Immutable.ImmutableStack`1[Hyperion.Tests.Something] cannot be cast to [B]System.Collections.Immutable.ImmutableStack`1[Hyperion.Tests.Something]. Type A originates from 'System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' in the context 'Default' at location 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Collections.Immutable.dll'. Type B originates from 'System.Collections.Immutable, Version=1.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' in the context 'Default' at location 'C:\Windows\system32\config\systemprofile\.nuget\packages\system.collections.immutable\1.4.0\lib\netstandard1.0\System.Collections.Immutable.dll'.

System.Collections.Immutable failure logs suggests that the issue may be in version of System.Collections.Immutable used. Possibly binding redirects are necessary.

**Comment by Aaronontheweb** [comment]
@Horusiath I was afraid of that. I'll get the Mono stuff fixed first. Bumping the runtime to .NET Core 2.0 across the board for unit tests should do the trick.

**Comment by Aaronontheweb** [comment]
@Horusiath fixed that issue. The `Tests.csproj` didn't actually import the `common.props` file we use for setting things like the XUnit version. Working on getting the .NET CLI to play nice on Mono now. Looks like it's getting hung up on compiling the F# project.

**Comment by Aaronontheweb** [comment]
This issue, specifically: https://github.com/Microsoft/msbuild/issues/2275

Appears to be a `/` vs `\` difference between Linux and Windows that is causing the problem :p

**Comment by Aaronontheweb** [comment]
Have all Mono tests and compilation passing now... Working on getting .NET Core to play nice too on Linux.

**Comment by Aaronontheweb** [comment]
ok, have .NET Core running on Linux now too. Everything should be working. Going to rebase.

**Pull request merged**
