### PR TITLE
Only make use of a generic elementType if the identified CreateRange …

### PR DESCRIPTION
**Pull request by goodisontoffee**
…method requires more than one type parameter.

Following from discussion on https://github.com/akkadotnet/Hyperion/issues/58 I have made the change I have arrived at locally for comment.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@goodisontoffee nice work

**Comment by alexvaluyskiy** [comment]
@Aaronontheweb @goodisontoffee I think we should have tests for the changes like this

**Comment by Aaronontheweb** [comment]
we should definitely have a reproduction spec

**Comment by Horusiath** [comment]
There's one in my PR #57 - I've forgot to check for it.

**Pull request merged**
