### PR TITLE
Remove dynamic keyword

### LINKED ISSUE #138: [Array]Serialization using dynamic keyword is very slow
Using dynamic single test
image

Remove dynamic single test
image

### PR DESCRIPTION
**Pull request by humhei**
fixes #138

### CODE REVIEW

**Comment by Horusiath** [comment]
Have you run actual benchmarks? We know that a single run can take time, but DLR specialization can speedup things on subsequent runs (that's precisely why dynamic is used there).

**Comment by humhei** [comment]
It's may be my fault,
I misunderstand that dynamic will recompile every time when <T> changed,
But it seems it only compile one time
even though generic type changed, it never compiled again 

I encounter this issue when i programming in UI side,

It have a obvious  Pause after i send message to server first
Maybe i can solve this problem by warmup `int []` first

**Comment by Aaronontheweb** [comment]
@Arkatufus in light of the changes made to https://github.com/akkadotnet/Hyperion/pull/235, this PR should probably be safe right? Performs the same cleanup in one more spot.

**Comment by Arkatufus** [comment]
Casting an object directly to Array might cause a problem with ValueType arrays, let me do a quick test first.

**Comment by Arkatufus** [comment]
Code is good, tested it and it works.

**Pull request merged**
