### PR TITLE
WIP Communicate between framework mscorlib and core framework System.Private.CoreLib

### PR DESCRIPTION
**Pull request by humhei**
ref #108 
Not very sure,
But it worked for me now,
Wait others to confirm

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
We need to get a unit test for this... Don't have a clear idea for how to do that off the top of my head

**Comment by nekenk1** [comment]
We could commit serialized files in both framework, unit test will pass if they can deserialize both of them from the 2 frameworks. We create explicit tests to create those files so if something else changes and break those tests, it's easy to commit new versions. What do you think ?

**Comment by Aaronontheweb** [comment]
@nekenk1 yeah, I'd just save a file - one written by .NET framework, one by core, and have the opposites read each other back into the original result. That would work.

**Comment by Aaronontheweb** [comment]
closed via #116

**Pull request closed without merging**
