### PR TITLE
Add test cases to check for regression on 0.11.0

### PR DESCRIPTION
**Pull request by Arkatufus**

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
There might not be an error during deserialization then. Maybe the issue is more subtle - maybe the data being read in isn't the same as the data being read back out, although it looks like this should account for it. Were there any other messages uncovered in https://github.com/akkadotnet/akka.net/pull/5138 that could have been responsible for this other than this one?

**Comment by Arkatufus** [comment]
This is pretty much all the messages that I had to add to the serializer on the Akka.NET side, so I'm at a bit of a loss here.

**Comment by Aaronontheweb** [comment]
@Arkatufus use the smoke test from before and just log all of the messages that passed through Hyperion, rather than throwing an exception on the first one. We might have missed a case.

**Comment by Arkatufus** [comment]
This is all of the message types that went through Hyperion in all of the MNTK tests:
https://docs.google.com/spreadsheets/d/1WBpcGiyKaVyV6xtEAR5xbPWFfPeroIOLY2n8FAtCgXc/edit?usp=sharing

**Comment by Arkatufus** [comment]
The list looks clean, no other sharding message (except for `Passivate`) goes through it

**Comment by Arkatufus** [comment]
| serialized   | Akka.Cluster.Sharding.Passivate                                                  | Akka.Cluster.Sharding                 |
|--------------|----------------------------------------------------------------------------------|---------------------------------------|
| deserialized | Akka.Cluster.Sharding.Passivate                                                  | Akka.Cluster.Sharding                 |
| serialized   | Akka.Cluster.Sharding.Tests.ClusterShardingFailureSpec+Add                       | Akka.Cluster.Sharding.Tests.MultiNode |
| deserialized | Akka.Cluster.Sharding.Tests.ClusterShardingFailureSpec+Add                       | Akka.Cluster.Sharding.Tests.MultiNode |
| serialized   | Akka.Cluster.Sharding.Tests.ClusterShardingFailureSpec+Value                     | Akka.Cluster.Sharding.Tests.MultiNode |
| deserialized | Akka.Cluster.Sharding.Tests.ClusterShardingFailureSpec+Value                     | Akka.Cluster.Sharding.Tests.MultiNode |
| serialized   | Akka.Cluster.Sharding.Tests.ClusterShardingGetStateSpec+Ping                     | Akka.Cluster.Sharding.Tests.MultiNode |
| deserialized | Akka.Cluster.Sharding.Tests.ClusterShardingGetStateSpec+Ping                     | Akka.Cluster.Sharding.Tests.MultiNode |
| serialized   | Akka.Cluster.Sharding.Tests.ClusterShardingGetStateSpec+Pong                     | Akka.Cluster.Sharding.Tests.MultiNode |
| deserialized | Akka.Cluster.Sharding.Tests.ClusterShardingGetStateSpec+Pong                     | Akka.Cluster.Sharding.Tests.MultiNode |
| serialized   | Akka.Cluster.Sharding.Tests.ClusterShardingLeavingSpec+GetLocations              | Akka.Cluster.Sharding.Tests.MultiNode |
| deserialized | Akka.Cluster.Sharding.Tests.ClusterShardingLeavingSpec+GetLocations              | Akka.Cluster.Sharding.Tests.MultiNode |
| serialized   | Akka.Cluster.Sharding.Tests.ClusterShardingLeavingSpec+Locations                 | Akka.Cluster.Sharding.Tests.MultiNode |
| deserialized | Akka.Cluster.Sharding.Tests.ClusterShardingLeavingSpec+Locations                 | Akka.Cluster.Sharding.Tests.MultiNode |
| serialized   | Akka.Cluster.Sharding.Tests.ClusterShardingLeavingSpec+Ping                      | Akka.Cluster.Sharding.Tests.MultiNode |
| deserialized | Akka.Cluster.Sharding.Tests.ClusterShardingLeavingSpec+Ping                      | Akka.Cluster.Sharding.Tests.MultiNode |
| serialized   | Akka.Cluster.Sharding.Tests.Counter+EntityEnvelope                               | Akka.Cluster.Sharding.Tests.MultiNode |
| deserialized | Akka.Cluster.Sharding.Tests.Counter+EntityEnvelope                               | Akka.Cluster.Sharding.Tests.MultiNode |
| serialized   | Akka.Cluster.Sharding.Tests.Counter+Get                                          | Akka.Cluster.Sharding.Tests.MultiNode |
| deserialized | Akka.Cluster.Sharding.Tests.Counter+Get                                          | Akka.Cluster.Sharding.Tests.MultiNode |
| serialized   | Akka.Cluster.Sharding.Tests.Counter+Stop                                         | Akka.Cluster.Sharding.Tests.MultiNode |
| deserialized | Akka.Cluster.Sharding.Tests.Counter+Stop                                         | Akka.Cluster.Sharding.Tests.MultiNode |
| serialized   | Akka.Cluster.Sharding.Tests.RollingUpdateShardAllocationSpec+GiveMeYourHome+Get  | Akka.Cluster.Sharding.Tests.MultiNode |
| deserialized | Akka.Cluster.Sharding.Tests.RollingUpdateShardAllocationSpec+GiveMeYourHome+Get  | Akka.Cluster.Sharding.Tests.MultiNode |
| serialized   | Akka.Cluster.Sharding.Tests.RollingUpdateShardAllocationSpec+GiveMeYourHome+Home | Akka.Cluster.Sharding.Tests.MultiNode |
| deserialized | Akka.Cluster.Sharding.Tests.RollingUpdateShardAllocationSpec+GiveMeYourHome+Home | Akka.Cluster.Sharding.Tests.MultiNode |
| serialized   | Akka.Persistence.RecoverySuccess                                                 | Akka.Persistence                      |
| deserialized | Akka.Persistence.RecoverySuccess                                                 | Akka.Persistence                      |
| serialized   | Akka.Persistence.ReplayedMessage                                                 | Akka.Persistence                      |
| deserialized | Akka.Persistence.ReplayedMessage                                                 | Akka.Persistence                      |
| serialized   | Akka.Persistence.ReplayMessages                                                  | Akka.Persistence                      |
| deserialized | Akka.Persistence.ReplayMessages                                                  | Akka.Persistence                      |
| serialized   | Akka.Persistence.WriteMessages                                                   | Akka.Persistence                      |
| deserialized | Akka.Persistence.WriteMessages                                                   | Akka.Persistence                      |
| serialized   | Akka.Persistence.WriteMessagesSuccessful                                         | Akka.Persistence                      |
| deserialized | Akka.Persistence.WriteMessagesSuccessful                                         | Akka.Persistence                      |
| serialized   | Akka.Persistence.WriteMessageSuccess                                             | Akka.Persistence                      |
| deserialized | Akka.Persistence.WriteMessageSuccess                                             | Akka.Persistence                      |

**Comment by Arkatufus** [comment]
Closing this for now, we can't find any regression bug caused by Hyperion 0.11.0

**Pull request closed without merging**
