### PR TITLE
CoreCLR MSBuild port

### PR DESCRIPTION
**Pull request by alexvaluyskiy**
This PR is based on https://github.com/akkadotnet/Hyperion/pull/15 but using MSBuild projects and the new DotNet CLI RC3. The most of conversion work was done by @alexpantyukhin 

TODO:
- [x] Create an updated Fake script
- [x] Fix a problem with RuntimeIdentifiers in MultiTargeted projects https://github.com/dotnet/cli/issues/4837
- [x] Connect to TeamCity CI (problems with sudo)
- [x] Run Nbench tests for net45 target
- [x] FSharp project is not working on AppVeyor (but working locally and on TravisCI)
- [x] Add VersionSuffix to nuget pack
- [x] Update docker image on TeamCity to this one https://github.com/akkadotnet/dockerfiles/pull/2
- [ ] Fix build on Mono: https://github.com/dotnet/sdk/issues/335 (It is not possible to run the project under Mono with the current (1.0.0 rc3) version of DotNet CLI. I hope MS will fix it before RTM)

Notable changes:
- AssemblyInfo and SharedAssembly info are not using anymore. Use csproj instead
- nuspec files are not using anymore. Use csproj instead
- There is no possibility to export xunit results to xml. We could use TRX instead
- NBench should have netstandard runner in order to run perf tests on both targets
- Removed Pro.NBench.xUnit and xunit from NBench tests, in order to fix the conflicts

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@alexvaluyskiy are you able to see the build logs from TeamCity?

**Comment by alexvaluyskiy** [comment]
@Aaronontheweb Yes
My scripts use a bit different parameters
./build.ps1 -target RunTests instead build.cmd RunTests
That is why it has failed

**Comment by alexvaluyskiy** [comment]
@Aaronontheweb I've almost finished here. Some Notes
1) It is not possible to run the project under Mono with the current (1.0.0 rc3) version of DotNet CLI. I hope MS will fix it before RTM
2) NBench is not working even on Windows. I've got this error
```
ERROR: Error while executing the tests.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at NBench.Sdk.Compiler.ReflectionDiscovery.<>c.<LoadAllTypeConfigurators>b__4_0(IEnumerable`1 types, Assembly assembly)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at NBench.Sdk.Compiler.ReflectionDiscovery.GetConfiguratorTypeForMeasurement(Type measurementType, Assembly specificAssembly)
   at NBench.Sdk.Compiler.ReflectionDiscovery.GetConfiguratorForMeasurement(Type measurementType, Assembly specificAssembly)
   at NBench.Sdk.Compiler.ReflectionDiscovery.CreateSettingsForBenchmark(BenchmarkClassMetadata benchmarkClass)
   at NBench.Sdk.Compiler.ReflectionDiscovery.FindBenchmarks(Assembly targetAssembly)
   at NBench.Sdk.TestRunner.Execute()
```
3) Is it possible to setup another Linux build agent with Ubuntu 16.04? Dotnet CLI does not run on Debian 7

**Comment by Aaronontheweb** [comment]
Looks like all of the tests pass on both platforms, although TeamCity formatting is turned off. @heynickc is opening some issues on that and what also looks like multiple installs of the .NET Core SDK at runtime and will send in subsequent PRs for those.

**Comment by Aaronontheweb** [comment]
Whoops, looks like Github didn't give me the option to squash commits. Might need to turn a setting on for that.

**Pull request merged**
