### PR TITLE
Introduced regex for TypeEx.GetShortAssemblyQualifiedName

### PR DESCRIPTION
**Pull request by kantora**
Fix of https://github.com/akkadotnet/Hyperion/issues/60

### CODE REVIEW

**Comment by kantora** [comment]
I've tested it in the conditions of #60 and it is working well.

**Comment by Danthar** [comment]
@kantora would you mind rebasing/fixing conflicts for this PR ?

**Comment by kantora** [comment]
Hi @Danthar. It was a long time ago, so I'll need to recover my development environment and to dive in that code.
I hope that I could do that this weekend.

**Comment by Aaronontheweb** [comment]
@Danthar @kantora I've rebased it

**Comment by kantora** [comment]
@Aaronontheweb Thanks!
@Danthar Sorry, that hasn't done that. Just crazy busy months without free weekends :(

**Pull request merged**
