### PR TITLE
added IgnoreISerializable to suppress using of ISerializable interface…

### PR DESCRIPTION
**Pull request by Ralf1108**
…s during serialization

### CODE REVIEW

**Comment by Ralf1108** [comment]
similar approach like Json.Net
http://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_Serialization_DefaultContractResolver_IgnoreSerializableInterface.htm

**Comment by Ralf1108** [comment]
Any progress here?

**Comment by Horusiath** [comment]
@Ralf1108 could you rebase this one give some more motivation about the change? What problem does it aim to solve?

**Comment by Ralf1108** [comment]
Hi,
the problem we tried to solve is customizing the serialization process over app domains.
We discovered that the non changeable serializer for crossing app domains is the .NET BinarySerializer. This works well for small amount of data. But starting with transferring more than 50000 objects to another app domain the bottleneck is only the serialization time. The more objects are transferred the more BinarySerializer slows down.

Our first approach was to set a own serializer but .NET Framework doesn't support out of the box. (We tried it even with reflection but gave up because there are so many hardcoded stuff).
So the only way to use other serialization mechanism for CrossAppDomain is to implement the ISerializable interface.

The second approach now does this. It implements the ISerializable and bottleneck solved. But now we have the burden to write everytime the code to satisfy the ISerializable interface in every object.
To have a more general approach it would be nice to have a base class implementing ISerializable and just call code like "serializer.Serialize(this)". Same for deserialization.

Problem here is that when we use Hyperion (which was the fastest and most appropiate serializer in our tests) and call "serialize(this)" the serializer will enter a recurisive loop because Hyperion also respects the ISerializable interface in the latest version. (Was added in commit a49fdcef95c512dd2d6be29f5c4cdacdfa2a4535).
Without this support everything worked fine.
With the support enabled by default we need a possibility to disable respecting ISerializable.

Hope the explanation was clear enough :-)

**Comment by Horusiath** [comment]
I'm fine with this. How about rest of the team? cc @akkadotnet/core

**Comment by Aaronontheweb** [comment]
@Horusiath looks good to me

**Pull request merged**
