### PR TITLE
Added support for DateTimeOffset as a primitive

### PR DESCRIPTION
**Pull request by JessieWadman**
Handles DateTimeOffset as a primitive, the same way as DateTime is currently handled. It serializes the offset in minutes, instead of DateTimeKind. The offset can be +/- 720 minutes, so a signed short has been used.

### CODE REVIEW

**Comment by Horusiath** [comment]
@JessieWadman  I think, you could go straightforward and serialize it as combination of DateTime part as ticks (one long) and TimeSpan offset ticks (another long). This will save possible problems in the future.

**Comment by JessieWadman** [comment]
@Horusiath You mean in case someone decides to create a DateTimeOffset with +40 hours or something?

**Comment by Horusiath** [comment]
@JessieWadman I'm thinking here more about time zone component used with precision to milliseconds or less.

**Comment by JessieWadman** [comment]
You're right, of course. As far as I know, all time zones are expressed in hours only, with the exception of three(?) that are some hours and 30 or 45 minute offset. Nevertheless, since the DateTimeOffset structure can express offset in ticks, it's not for us to misplace those along the way.

**Pull request merged**
